#pragma once
#include"mov.h"
#include"add_adc.h"
#include"sub_sbb.h"
#include"mul_imul.h"
#include"div_idiv.h"
#include"and_or_xor.h"
#include"cmp.h"
#include"neg.h"
#include"not.h"
#include"dec.h"
#include"inc.h"
#include"daa.h"
#include"shl_sal.h"